// MONEO's icon vocabulary. The app shows no emojis: every icon is a thick-line glyph
// (src/components/ui/Glyph.tsx). Data stores the glyph key ('food', 'piggy', …); rows
// saved before keeps an emoji, so glyphKey() maps those legacy emojis to a key.

export const GLYPH_KEYS = [
  'alarm',
  'alert',
  'apple',
  'bag',
  'ban',
  'bank',
  'bell',
  'bird',
  'book',
  'bot',
  'brain',
  'briefcase',
  'brush',
  'bulb',
  'calendar',
  'camera',
  'car',
  'card',
  'cart',
  'cash',
  'castle',
  'chain',
  'chart',
  'chat',
  'check',
  'clipboard',
  'clock',
  'close',
  'cloud',
  'coffee',
  'coins',
  'dice',
  'download',
  'drama',
  'edit',
  'exchange',
  'film',
  'folder',
  'food',
  'gamepad',
  'gem',
  'gift',
  'globe',
  'graduation',
  'guitar',
  'hand',
  'handshake',
  'headphones',
  'heart',
  'home',
  'hourglass',
  'image',
  'inbox',
  'joystick',
  'laptop',
  'lifebuoy',
  'lock',
  'mic',
  'music',
  'note',
  'package',
  'palette',
  'party',
  'pen',
  'person',
  'phone',
  'piggy',
  'play',
  'pill',
  'plane',
  'plus',
  'pointer',
  'receipt',
  'repeat',
  'sandwich',
  'satellite',
  'scissors',
  'search',
  'send',
  'settings',
  'shield',
  'shirt',
  'smile',
  'sofa',
  'sparkles',
  'sprout',
  'star',
  'store',
  'tag',
  'target',
  'taxi',
  'toy',
  'trending',
  'trophy',
  'tv',
  'upload',
  'user',
  'users',
  'video',
  'wallet',
  'waves',
  'zap',
] as const;

export type GlyphKey = (typeof GLYPH_KEYS)[number];

const KEY_SET = new Set<string>(GLYPH_KEYS);

/** Legacy emojis (saved rows, database defaults, notifications) → glyph key. */
const EMOJI_TO_GLYPH: Record<string, GlyphKey> = {
  '⏰': 'alarm',
  '⚠': 'alert',
  '⛔': 'ban',
  '🍎': 'apple',
  '🛍': 'bag',
  '🏦': 'bank',
  '🏛': 'bank',
  '🔔': 'bell',
  '🦉': 'bird',
  '📚': 'book',
  '🤖': 'bot',
  '🧠': 'brain',
  '💼': 'briefcase',
  '🖌': 'brush',
  '🎨': 'palette',
  '💡': 'bulb',
  '📅': 'calendar',
  '📸': 'camera',
  '🚗': 'car',
  '💳': 'card',
  '🛒': 'cart',
  '💵': 'cash',
  '💸': 'cash',
  '🏰': 'castle',
  '⛓': 'chain',
  '📊': 'chart',
  '💬': 'chat',
  '✓': 'check',
  '✅': 'check',
  '📋': 'clipboard',
  '🕐': 'clock',
  '⏳': 'hourglass',
  '✕': 'close',
  '❌': 'close',
  '☁': 'cloud',
  '☕': 'coffee',
  '💰': 'coins',
  '🎰': 'dice',
  '📥': 'download',
  '🎭': 'drama',
  '✏': 'edit',
  '✍': 'pen',
  '💱': 'exchange',
  '🔄': 'repeat',
  '🎬': 'film',
  '📂': 'folder',
  '🍽': 'food',
  '🍔': 'sandwich',
  '🍥': 'food',
  '🎮': 'gamepad',
  '🕹': 'joystick',
  '💍': 'gem',
  '🎁': 'gift',
  '🌐': 'globe',
  '🎓': 'graduation',
  '🎸': 'guitar',
  '👋': 'hand',
  '🙌': 'hand',
  '👆': 'pointer',
  '🤝': 'handshake',
  '🎧': 'headphones',
  '❤': 'heart',
  '💜': 'heart',
  '💚': 'heart',
  '🏠': 'home',
  '🏡': 'home',
  '🖼': 'image',
  '📭': 'inbox',
  '💻': 'laptop',
  '🛟': 'lifebuoy',
  '🔒': 'lock',
  '🎙': 'mic',
  '🎵': 'music',
  '🎶': 'music',
  '📝': 'note',
  '📦': 'package',
  '🎉': 'party',
  '🧘': 'person',
  '📱': 'phone',
  '📲': 'phone',
  '🐷': 'piggy',
  '▶': 'play',
  '💊': 'pill',
  '✈': 'plane',
  '➕': 'plus',
  '🧾': 'receipt',
  '📡': 'satellite',
  '✂': 'scissors',
  '🔍': 'search',
  '📤': 'upload',
  '⚙': 'settings',
  '🛡': 'shield',
  '👕': 'shirt',
  '😌': 'smile',
  '🛋': 'sofa',
  '✨': 'sparkles',
  '🌱': 'sprout',
  '⭐': 'star',
  '🌟': 'star',
  '🟣': 'star',
  '🏪': 'store',
  '🏷': 'tag',
  '🎯': 'target',
  '🚕': 'taxi',
  '🧸': 'toy',
  '📈': 'trending',
  '🏆': 'trophy',
  '📺': 'tv',
  '👤': 'user',
  '👥': 'users',
  '📹': 'video',
  '🌊': 'waves',
  '⚡': 'zap',
  '🐒': 'smile',
};

/** Glyph key for a stored icon value: a key as is, a legacy emoji mapped, else null. */
export function glyphKey(value: string | null | undefined): GlyphKey | null {
  if (!value) return null;
  const v = value.trim();
  if (KEY_SET.has(v)) return v as GlyphKey;
  // Drop variation selectors and skin tones before looking the emoji up.
  const bare = v.replace(/[︎️\u{1F3FB}-\u{1F3FF}]/gu, '');
  return EMOJI_TO_GLYPH[bare] ?? null;
}

/** Whether a stored icon value can be drawn as a glyph (key or known emoji). */
export function isGlyph(value: string | null | undefined): boolean {
  return glyphKey(value) !== null;
}
