// GENERATED by scripts/build-edge-interpreter.mjs from src/lib/auto — do not edit.
// src/lib/auto/normalize.ts
var MONTHS = {
  ene: 1,
  enero: 1,
  jan: 1,
  feb: 2,
  febrero: 2,
  mar: 3,
  marzo: 3,
  abr: 4,
  abril: 4,
  apr: 4,
  may: 5,
  mayo: 5,
  jun: 6,
  junio: 6,
  jul: 7,
  julio: 7,
  ago: 8,
  agosto: 8,
  aug: 8,
  set: 9,
  sep: 9,
  sept: 9,
  septiembre: 9,
  setiembre: 9,
  oct: 10,
  octubre: 10,
  nov: 11,
  noviembre: 11,
  dic: 12,
  diciembre: 12,
  dec: 12
};
function normalizeText(text) {
  return text.replace(/\r\n?/g, "\n").replace(/[\u00a0\u2007\u202f\t]/g, " ").split("\n").map((l) => l.replace(/ {2,}/g, " ").trim()).filter((l, i, arr) => l !== "" || i > 0 && arr[i - 1] !== "").join("\n").trim();
}
function stripBoldMarkers(text) {
  return text.replace(/(^|\s)\*(?=[^\s*])/g, "$1").replace(/(?<=[^\s*])\*(?=\s|[.,;:)]|$)/gm, "");
}
function flatten(text) {
  return normalizeText(text).replace(/\n+/g, " ");
}
var AMOUNT_RE = /(US\$|\$|S\/\.?)\s*([0-9]{1,3}(?:,[0-9]{3})*(?:\.[0-9]{1,2})?|[0-9]+(?:\.[0-9]{1,2})?)/;
function parseAmount(text) {
  const m = text.match(AMOUNT_RE);
  if (!m) return null;
  const amount = Math.round(parseFloat(m[2].replace(/,/g, "")) * 100) / 100;
  if (!isFinite(amount) || amount <= 0) return null;
  return { amount, currency: m[1].startsWith("S/") ? "PEN" : "USD" };
}
var pad = (n) => String(n).padStart(2, "0");
function localDate(d) {
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}`;
}
function localTime(d) {
  return `${pad(d.getHours())}:${pad(d.getMinutes())}`;
}
function parseTime(text) {
  const m = text.match(/(\d{1,2}):(\d{2})(?::\d{2})?\s*(a\.?\s*m\.?|p\.?\s*m\.?)?/i);
  if (!m) return null;
  let h = parseInt(m[1], 10);
  const min = parseInt(m[2], 10);
  const ampm = m[3]?.toLowerCase().replace(/[\s.]/g, "");
  if (ampm === "pm" && h < 12) h += 12;
  if (ampm === "am" && h === 12) h = 0;
  if (h > 23 || min > 59) return null;
  return `${pad(h)}:${pad(min)}`;
}
function validDate(y, mo, d) {
  if (!y || !mo || !d || mo > 12 || d > 31) return null;
  return `${y}-${pad(mo)}-${pad(d)}`;
}
function parseDate(text, ref) {
  let m = text.match(/\b(\d{1,2})\/(\d{1,2})\/(\d{4})\b/);
  if (m) return validDate(+m[3], +m[2], +m[1]);
  m = text.match(/\b(\d{1,2})\s+(?:de\s+)?([a-záéíóú]{3,10})\.?,?\s+(?:de\s+|del\s+)?(\d{4})\b/i);
  if (m) {
    const mo = MONTHS[m[2].toLowerCase()];
    if (mo) return validDate(+m[3], mo, +m[1]);
  }
  m = text.match(/\b(\d{1,2})\/(\d{1,2})\b/);
  if (m) {
    let year = ref.getFullYear();
    const candidate = new Date(year, +m[2] - 1, +m[1]);
    if (candidate.getTime() - ref.getTime() > 24 * 3600 * 1e3) year -= 1;
    return validDate(year, +m[2], +m[1]);
  }
  return null;
}
function valueAfter(text, label) {
  const lines = normalizeText(text).split("\n");
  for (let i = 0; i < lines.length; i++) {
    const m = lines[i].match(new RegExp(`^${label.source}\\s*:?\\s*(.*)$`, "i"));
    if (!m) continue;
    const sameLine = m[m.length - 1].trim();
    if (sameLine) return sameLine;
    const next = lines.slice(i + 1).find((l) => l.trim() !== "");
    return next?.trim() ?? null;
  }
  return null;
}
function last4(text) {
  const m = text?.match(/(\d{4})\s*$/);
  return m ? m[1] : void 0;
}

// src/lib/auto/merchant.ts
var PROCESSOR_PREFIX = /^(?:IZI|EBN\*SG|EBN|PAYU|DLO|DLC|MP|PP|SQ|CULQI|NIUBIZ|VISANET|OPENPAY|PAGOEFECTIVO|PAYPAL)\s*\*\s*/i;
var KNOWN = [
  [/OPENAI|CHATGPT/, "ChatGPT"],
  [/FACEBK|FACEBOOK|META\s*ADS|\bMETA\s*PLATFORMS/, "Facebook Ads"],
  [/GOOGLE\s*\*?\s*ADS/, "Google Ads"],
  [/NETFLIX/, "Netflix"],
  [/SPOTIFY/, "Spotify"],
  [/DISNEY/, "Disney+"],
  [/YOUTUBE/, "YouTube"],
  [/GOOGLE\s*\*?\s*(?:STORAGE|ONE)/, "Google One"],
  [/APPLE\.COM|APPLE\s*SERVICES/, "Apple"],
  [/AMAZON|AMZN/, "Amazon"],
  [/UBER\s*EATS/, "Uber Eats"],
  [/UBER/, "Uber"],
  [/RAPPI/, "Rappi"],
  [/PEDIDOSYA/, "PedidosYa"],
  [/CABIFY/, "Cabify"],
  [/WONG/, "Wong"],
  [/PLAZA\s*VEA/, "Plaza Vea"],
  [/TOTTUS/, "Tottus"],
  [/METRO\b/, "Metro"],
  [/TAMBO/, "Tambo"],
  [/OXXO/, "Oxxo"],
  [/BITEL/, "Bitel"],
  [/CLARO/, "Claro"],
  [/MOVISTAR/, "Movistar"],
  [/ENTEL/, "Entel"],
  [/PDFGURU/, "PDFGuru"],
  [/STARBUCKS/, "Starbucks"]
];
var CATEGORY_RULES = [
  [/FACEBOOK ADS|GOOGLE ADS/, "Servicios"],
  [
    /CHATGPT|OPENAI|NETFLIX|SPOTIFY|DISNEY|YOUTUBE|GOOGLE ONE|APPLE|PDFGURU|SUBSCR|HBO|PRIME/,
    "Suscripciones"
  ],
  [/WONG|PLAZA VEA|TOTTUS|METRO|MAKRO|VIVANDA|MASS\b|TAMBO|OXXO|MERCADO/, "Supermercado"],
  [
    /UBER(?! EATS)|CABIFY|DIDI|INDRIVE|TAXI|GRIFO|PRIMAX|REPSOL|PECSA|PETROPERU|PEAJE|ESTACION|E S |SERVICENTRO/,
    "Transporte"
  ],
  [
    /RAPPI|PEDIDOSYA|UBER EATS|STARBUCKS|KFC|BEMBOS|PIZZA|POLLER|CHIFA|RESTAURANT|CAFE|BURGER|MCDONALD|YOPO/,
    "Comida"
  ],
  [/BITEL|CLARO|MOVISTAR|ENTEL|LUZ DEL SUR|ENEL|SEDAPAL|CALIDDA|WIN\b/, "Servicios"],
  [/BOTICA|FARMACIA|INKAFARMA|MIFARMA|CLINICA|SALUD/, "Salud"],
  [/CINEPLANET|CINEMARK|CINE|STEAM|PLAYSTATION|XBOX/, "Entretenimiento"],
  [/UNIVERSIDAD|INSTITUTO|COLEGIO|UDEMY|COURSERA|PLATZI/, "Educaci\xF3n"]
];
function titleCase(s) {
  return s.toLowerCase().replace(/(^|[\s\-/])([a-záéíóúñ])/g, (_, sep, ch) => sep + ch.toUpperCase());
}
function cleanMerchant(raw) {
  let s = raw.replace(/\s+/g, " ").trim().replace(/[.,;]+$/, "");
  s = s.replace(PROCESSOR_PREFIX, "");
  s = s.replace(/\*\s*\d{3,}$/, "").replace(/\s+\d{5,}$/, "");
  s = s.replace(/\s+(?=[A-Z0-9]*\d)(?=[A-Z0-9]*[A-Z])[A-Z0-9]{6,}$/i, "");
  s = s.replace(/\*/g, " ").replace(/\s+/g, " ").trim();
  const upper = s.toUpperCase();
  for (const [re, name] of KNOWN) if (re.test(upper)) return name;
  return titleCase(s);
}
function suggestCategory(merchant, raw = "") {
  const hay = `${merchant} ${raw}`.toUpperCase();
  for (const [re, cat] of CATEGORY_RULES) if (re.test(hay)) return cat;
  return null;
}
function merchantKey(name) {
  return name.toLowerCase().normalize("NFD").replace(/[̀-ͯ]/g, "").replace(/[^a-z0-9]/g, "");
}
function sameMerchant(a, b) {
  const ka = merchantKey(a);
  const kb = merchantKey(b);
  if (!ka || !kb) return false;
  if (ka === kb) return true;
  const [short, long] = ka.length <= kb.length ? [ka, kb] : [kb, ka];
  return short.length >= 5 && long.startsWith(short.slice(0, Math.max(5, short.length - 2)));
}

// src/lib/auto/banks/common.ts
var AMT = String.raw`(?:US\$|\$|S\/\.?)\s*[0-9][0-9,]*(?:\.[0-9]{1,2})?`;
var AMOUNT_SRC = AMT;
function when(msg, dateText, timeText) {
  const date = dateText && parseDate(dateText, msg.receivedAt) || localDate(msg.receivedAt);
  const time = timeText && parseTime(timeText) || dateText && parseTime(dateText) || (dateText ? null : localTime(msg.receivedAt));
  return { date, time };
}
function merchantFields(raw) {
  const merchant = cleanMerchant(raw);
  return { merchant, suggestedCategory: suggestCategory(merchant, raw) };
}
function personName(raw) {
  return raw.replace(/\s*[-_=]{3,}.*$/, "").replace(/\*/g, "").replace(/\s+/g, " ").trim().toLowerCase().replace(/(^|\s)([a-záéíóúñ])/g, (_, s, c) => s + c.toUpperCase());
}

// src/lib/auto/banks/bcp.ts
var parseBcp = (msg) => {
  const flat = flatten(msg.text);
  const m = flat.match(
    new RegExp(
      `Realizaste un consumo de\\s*(${AMOUNT_SRC})\\s+con tu Tarjeta de (Cr[e\xE9]dito|D[e\xE9]bito)(?: BCP)?\\s+en\\s+(.+?)\\.(?:\\s|$)`,
      "i"
    )
  );
  if (!m) return null;
  const amt = parseAmount(valueAfter(msg.text, /Total del consumo/) ?? m[1]);
  if (!amt) return null;
  const empresa = valueAfter(msg.text, /Empresa/) || m[3];
  const credit = /cr/i.test(m[2]);
  return {
    bank: "bcp",
    kind: "consumo",
    type: "gasto",
    ...amt,
    ...merchantFields(empresa),
    ...when(msg, valueAfter(msg.text, /Fecha y hora/)),
    cardLast4: last4(valueAfter(msg.text, /N[uú]mero de Tarjeta(?: de (?:Cr[eé]dito|D[eé]bito))?/)),
    cardType: credit ? "credito" : "debito",
    operationId: valueAfter(msg.text, /N[uú]mero de operaci[oó]n/)?.replace(/\D/g, "") || void 0,
    recurring: false
  };
};

// src/lib/auto/banks/bbva.ts
var parseBbva = (msg) => {
  const flat = flatten(`${msg.subject ?? ""}
${msg.text}`);
  if (!/Transferencia|Transf\./i.test(flat)) return null;
  const amt = parseAmount(
    valueAfter(msg.text, /Importe transferido/) ?? valueAfter(msg.text, /Importe cargado/) ?? ""
  );
  if (!amt) return null;
  const ownAccount = /cuenta es propia/i.test(flat);
  const destinationBank = valueAfter(msg.text, /Banco de destino/) ?? void 0;
  const destinationLast4 = last4(valueAfter(msg.text, /Cuenta de destino/));
  const beneficiary = valueAfter(msg.text, /Nombre del beneficiario/);
  const bankName = destinationBank ? personName(destinationBank) : "otra cuenta";
  return {
    bank: "bbva",
    kind: "transferencia",
    type: ownAccount ? "transferencia" : "gasto",
    ...amt,
    // Own account: no third-party name needed. Otherwise the beneficiary describes it.
    merchant: ownAccount ? `Transferencia a ${bankName}${destinationLast4 ? ` \u2022${destinationLast4}` : ""}` : beneficiary ? personName(beneficiary) : `Transferencia a ${bankName}`,
    ...when(msg, valueAfter(msg.text, /Fecha y hora de la operaci[oó]n/)),
    destinationBank,
    destinationLast4,
    ownAccount,
    operationId: valueAfter(msg.text, /N[uú]mero de operaci[oó]n/)?.replace(/\D/g, "") || void 0,
    suggestedCategory: ownAccount ? null : "Otros",
    recurring: false
  };
};

// src/lib/auto/banks/interbank.ts
var parseInterbank = (msg) => {
  const flat = flatten(`${msg.subject ?? ""}
${msg.text}`);
  const isEmail = msg.source === "email";
  let m = flat.match(new RegExp(`(.+?)\\s+te ha plineado\\s+(${AMOUNT_SRC})`, "i"));
  if (m) {
    const amt = parseAmount(m[2]);
    if (!amt) return null;
    return {
      bank: "interbank",
      kind: "plin_recibido",
      type: "ingreso",
      ...amt,
      merchant: personName(m[1].replace(/^Interbank\s+/i, "")),
      ...when(msg),
      suggestedCategory: null,
      recurring: false
    };
  }
  const detailBlock = /Comercio\s*:/i.test(msg.text) && /Monto\s*:/i.test(msg.text);
  const fromInterbank = isEmail || /interbank/i.test(flat) || /Tarjeta\s*:\s*\*{4}\d{4}/i.test(msg.text);
  if (detailBlock && fromInterbank) {
    const amt = parseAmount(valueAfter(msg.text, /Monto/) ?? "");
    const comercio = valueAfter(msg.text, /Comercio/);
    if (!amt || !comercio) return null;
    const recurring = /pago recurrente/i.test(flat);
    return {
      bank: "interbank",
      kind: recurring ? "pago_recurrente" : "consumo",
      type: "gasto",
      ...amt,
      ...merchantFields(comercio),
      ...when(msg, valueAfter(msg.text, /Fecha/), valueAfter(msg.text, /Hora/)),
      cardLast4: last4(valueAfter(msg.text, /Tarjeta/)),
      cardType: cardTypeOf(flat),
      recurring
    };
  }
  m = flat.match(
    new RegExp(
      `(Realizaste un consumo|Se realiz[o\xF3] un pago recurrente) de\\s*(${AMOUNT_SRC})\\s+en\\s+(.+?)(?:\\s+con tu Tarjeta de (D[e\xE9]bito|Cr[e\xE9]dito).*|\\s*\\.?\\s*)$`,
      "i"
    )
  );
  if (m) {
    const amt = parseAmount(m[2]);
    if (!amt) return null;
    const recurring = /recurrente/i.test(m[1]);
    return {
      bank: "interbank",
      kind: recurring ? "pago_recurrente" : "consumo",
      type: "gasto",
      ...amt,
      ...merchantFields(m[3]),
      ...when(msg),
      cardType: m[4] ? /cr/i.test(m[4]) ? "credito" : "debito" : void 0,
      recurring
    };
  }
  m = flat.match(
    new RegExp(
      `PAGO\\s+(${AMOUNT_SRC})\\s+A:\\s*(.+?)\\s*\\((\\d{1,2}/\\d{1,2})\\s+([\\d:]+)\\)`,
      "i"
    )
  );
  if (m) {
    const amt = parseAmount(m[1]);
    if (!amt) return null;
    return {
      bank: "interbank",
      kind: "consumo",
      type: "gasto",
      ...amt,
      ...merchantFields(m[2]),
      ...pagoWhen(msg.receivedAt, m[3], m[4]),
      recurring: false
    };
  }
  return null;
};
function pagoWhen(receivedAt, dayMonth, clock) {
  const date = parseDate(dayMonth, receivedAt) ?? "";
  const [h, mi] = clock.split(":").map(Number);
  const at = (hour2) => (/* @__PURE__ */ new Date(`${date}T00:00:00`)).getTime() + (hour2 * 60 + mi) * 6e4;
  const ref = receivedAt.getTime();
  const hour = h < 12 && Math.abs(at(h + 12) - ref) < Math.abs(at(h) - ref) ? h + 12 : h;
  return { date, time: `${String(hour).padStart(2, "0")}:${String(mi).padStart(2, "0")}` };
}
function cardTypeOf(text) {
  const m = text.match(/Tarjeta[^.\n]{0,40}?(D[eé]bito|Cr[eé]dito)/i);
  return m && /cr/i.test(m[1]) ? "credito" : "debito";
}

// src/lib/auto/banks/yape.ts
function between(flat, label, stop) {
  const m = flat.match(new RegExp(`${label.source}\\s*:?\\s*(.+?)\\s*(?=${stop.source}|$)`, "i"));
  return m ? m[1].trim() : null;
}
var STOPS = /-{3,}|Yapero|Tu n[uú]mero|N[uú]mero de celular|Fecha y hora|Celular del|Nombre del|N[º°o]\.? de operaci|Detalle del servicio|Empresa|Servicio|C[oó]digo de usuario|Titular|Resuelve/;
var parseYape = (msg) => {
  const flat = flatten(`${msg.subject ?? ""}
${msg.text}`);
  const m = flat.match(
    new RegExp(
      `(?:^|Confirmaci[o\xF3]n de Pago\\s+)?([^.]+?)\\s+te envi[o\xF3] un pago por\\s+(${AMOUNT_SRC})`,
      "i"
    )
  );
  if (m) {
    const amt = parseAmount(m[2]);
    if (!amt) return null;
    return {
      bank: "yape",
      kind: "yape_recibido",
      type: "ingreso",
      ...amt,
      merchant: personName(m[1].replace(/^Confirmaci[oó]n de Pago\s+/i, "")),
      ...when(msg),
      suggestedCategory: null,
      recurring: false
    };
  }
  const opId = between(flat, /N[º°o]\.?\s*de operaci[oó]n(?: Yape)?/, STOPS)?.replace(/\D/g, "") || void 0;
  const dateText = between(flat, /Fecha y hora(?: de la operaci[oó]n)?/, STOPS);
  if (/servicio fue yapeado/i.test(flat)) {
    const amt = parseAmount(between(flat, /Monto total/, STOPS) ?? "");
    const empresa = valueAfter(msg.text, /Empresa/) ?? between(flat, /Empresa/, STOPS);
    if (!amt || !empresa) return null;
    const fields = merchantFields(empresa);
    return {
      bank: "yape",
      kind: "pago_servicio",
      type: "gasto",
      ...amt,
      ...fields,
      suggestedCategory: fields.suggestedCategory ?? "Servicios",
      ...when(msg, dateText),
      operationId: opId,
      recurring: false
    };
  }
  if (/acabas de yapear|yapeaste/i.test(flat)) {
    const amt = parseAmount(between(flat, /Monto de yapeo\*?/, STOPS) ?? "");
    if (!amt) return null;
    const beneficiary = between(flat, /Nombre del Beneficiario/, STOPS);
    return {
      bank: "yape",
      kind: "yape_enviado",
      type: "gasto",
      ...amt,
      merchant: beneficiary ? personName(beneficiary) : "Yape",
      ...when(msg, dateText),
      operationId: opId,
      suggestedCategory: null,
      recurring: false
    };
  }
  return null;
};

// src/lib/auto/freeText.ts
var strip = (s) => s.toLowerCase().normalize("NFD").replace(/[̀-ͯ]/g, "");
var BANKS = [
  [/\bbcp\b/, "bcp"],
  [/\bbbva\b/, "bbva"],
  [/\binterbank\b|\bibk\b/, "interbank"],
  [/\byape\b|\byapee\b|\byapeo\b|\byapearon\b|\byapee\b/, "yape"],
  [/\bplin\b|\bplinee\b|\bplinearon\b/, "plin"],
  [/\bscotiabank\b|\bscotia\b/, "scotiabank"]
];
var INCOME = /\b(me pagaron|me pago|cobre|cobro|recibi|me depositaron|me yapearon|me plinearon|me transfirieron|sueldo|salario|quincena|ingreso|abono|vendi|venta|me devolvieron|reembolso|propina)\b/;
var CONCEPTS = [
  [
    /\b(taxi|uber|cabify|didi|indrive|combi|micro|bus|pasaje|metropolitano|gasolina|grifo|peaje|estacionamiento|cochera|tren)\b/,
    "Transporte"
  ],
  [
    /\b(almuerzo|cena|desayuno|lonche|menu|comida|pollo|chifa|cafe|pizza|hamburguesa|restaurante|delivery|rappi|pedidosya|snack|helado|ceviche)\b/,
    "Comida"
  ],
  [
    /\b(mercado|supermercado|bodega|abarrotes|compras|wong|tottus|plaza vea|metro|makro|tambo|oxxo)\b/,
    "Supermercado"
  ],
  [
    /\b(luz|agua|internet|celular|telefono|recarga|cable|gas|bitel|claro|movistar|entel)\b/,
    "Servicios"
  ],
  [/\b(farmacia|botica|medicina|medico|doctor|clinica|dentista|analisis|consulta)\b/, "Salud"],
  [
    /\b(cine|netflix|spotify|disney|juego|concierto|entrada|fiesta|salida|bar|discoteca)\b/,
    "Entretenimiento"
  ],
  [/\b(alquiler|renta|departamento|condominio|mantenimiento|casa)\b/, "Vivienda"],
  [/\b(colegio|universidad|curso|clase|libro|libros|pension|matricula|utiles)\b/, "Educaci\xF3n"]
];
var FILLER = new Set(
  "gaste gasto pague pago compre compra consumi consumo realice hice di dio puse me mi mis el la los las un una unos unas en de del por para con a al y o que hoy ayer anteayer soles sol s dolares dolar usd pen bcp bbva interbank ibk yape yapee yapeo plin scotiabank scotia tarjeta cuenta debito credito efectivo pagaron cobre cobro recibi depositaron yapearon plinearon transfirieron".split(" ")
);
function findAmount(t) {
  const spoken = t.match(/(?<![\d/:.,])(\d+)\s+con\s+(\d{1,2})\b/);
  if (spoken) {
    const amount = parseFloat(`${spoken[1]}.${spoken[2].padStart(2, "0")}`);
    const currency = /\b(dolares|dolar|usd)\b|\$/.test(t) ? "USD" : "PEN";
    if (amount > 0) return { amount, currency, raw: spoken[0] };
  }
  const patterns = [
    [/(?:us\$|\$)\s*(\d+(?:[.,]\d{1,2})?)/, "USD"],
    [/(\d+(?:[.,]\d{1,2})?)\s*(?:dolares|dolar|usd)\b/, "USD"],
    [/s\/\.?\s*(\d+(?:[.,]\d{1,2})?)/, "PEN"],
    [/(\d+(?:[.,]\d{1,2})?)\s*(?:soles|sol|pen)\b/, "PEN"],
    // plain number not part of a date (12/10) or a time (5:30)
    [/(?<![\d/:.,])(\d+(?:[.,]\d{1,2})?)(?![\d/:]|[.,]\d)/, "PEN"]
  ];
  for (const [re, currency] of patterns) {
    const m = t.match(re);
    if (m) {
      const amount = Math.round(parseFloat(m[1].replace(",", ".")) * 100) / 100;
      if (amount > 0 && amount < 1e7) return { amount, currency, raw: m[0] };
    }
  }
  return null;
}
function conceptCategory(text) {
  const t = strip(text);
  return CONCEPTS.find(([re]) => re.test(t))?.[1] ?? null;
}
function parseFreeText(text, receivedAt) {
  const original = text.replace(/\s+/g, " ").trim();
  if (!original || original.length > 160) return null;
  const t = strip(original);
  const amt = findAmount(t);
  if (!amt) return null;
  const type = INCOME.test(t) ? "ingreso" : "gasto";
  const bank = BANKS.find(([re]) => re.test(t))?.[1] ?? "otro";
  let date = localDate(receivedAt);
  let time = localTime(receivedAt);
  const daysBack = /\banteayer\b/.test(t) ? 2 : /\bayer\b/.test(t) ? 1 : 0;
  if (daysBack) {
    const d = new Date(receivedAt);
    d.setDate(d.getDate() - daysBack);
    date = localDate(d);
    time = null;
  } else {
    const explicit = t.match(/\b\d{1,2}\/\d{1,2}(?:\/\d{4})?\b/);
    const parsed = explicit ? parseDate(explicit[0], receivedAt) : null;
    if (parsed) {
      date = parsed;
      time = null;
    }
  }
  const words = original.replace(new RegExp(amt.raw.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"), "i"), " ").replace(/\b\d{1,2}\/\d{1,2}(?:\/\d{4})?\b/g, " ").replace(/[$]|s\/\.?/gi, " ").split(/\s+/).map((w) => w.replace(/^[^\p{L}\p{N}]+|[^\p{L}\p{N}]+$/gu, "")).filter((w) => w && !FILLER.has(strip(w)) && !/^\d+([.,]\d+)?$/.test(w));
  const concept = words.join(" ").trim();
  const merchant = concept ? cleanMerchant(concept) : type === "ingreso" ? "Ingreso" : "Gasto";
  const category = type === "ingreso" ? "Ingreso" : CONCEPTS.find(([re]) => re.test(t))?.[1] ?? suggestCategory(merchant, original);
  return {
    bank,
    kind: "texto",
    type,
    amount: amt.amount,
    currency: amt.currency,
    merchant: merchant.slice(0, 120),
    date,
    time,
    suggestedCategory: category,
    recurring: false
  };
}

// src/lib/auto/receipt.ts
var NUM = /(\d{1,3}(?:[ ,.]\d{3})*[.,]\d{2}|\d+[.,]\d{2})/g;
function toAmount(raw) {
  const cleaned = raw.replace(/\s/g, "");
  const lastSep = Math.max(cleaned.lastIndexOf("."), cleaned.lastIndexOf(","));
  const int = cleaned.slice(0, lastSep).replace(/[.,]/g, "");
  return Math.round(parseFloat(`${int}.${cleaned.slice(lastSep + 1)}`) * 100) / 100;
}
var NOT_NAME = /\b(ruc|r\.u\.c|boleta|factura|ticket|electr[oó]nica|venta|nota|fecha|hora|cajero|caja|direcci[oó]n|av\.?|jr\.?|calle|tel[eé]fono|telf|www\.|http|cliente|dni|serie)\b/i;
function parseReceipt(text, receivedAt) {
  const lines = text.split("\n").map((l) => l.replace(/\s+/g, " ").trim()).filter(Boolean);
  if (lines.length < 2) return null;
  let total = null;
  for (const line of lines) {
    if (!/\b(importe\s+)?total\b/i.test(line)) continue;
    if (/sub\s*-?\s*total|descuento|items?|art[ií]culos|gravad|exonerad|inafect|igv|ahorro/i.test(
      line
    ))
      continue;
    const nums = line.match(NUM);
    if (nums?.length) total = toAmount(nums[nums.length - 1]);
  }
  if (!total || total <= 0 || total > 1e6) return null;
  const currency = /\b(us\$|usd|d[oó]lares)\b|\$\s*\d/i.test(text) && !/s\/\.?/i.test(text) ? "USD" : "PEN";
  const nameLine = lines.slice(0, 6).find((l) => /[a-záéíóúñ]{3,}/i.test(l) && !NOT_NAME.test(l) && !/\d{6,}/.test(l));
  const merchant = nameLine ? cleanMerchant(nameLine).slice(0, 120) : "Compra";
  const dateLine = text.replace(/(\d{1,2})-(\d{1,2})-(\d{4})/g, "$1/$2/$3");
  const date = parseDate(dateLine.match(/\b\d{1,2}\/\d{1,2}\/\d{4}\b/)?.[0] ?? "", receivedAt);
  return {
    bank: "otro",
    kind: "texto",
    type: "gasto",
    amount: total,
    currency,
    merchant,
    date: date ?? localDate(receivedAt),
    time: date ? null : localTime(receivedAt),
    suggestedCategory: suggestCategory(merchant, text) ?? conceptCategory(text),
    recurring: false
  };
}

// src/lib/auto/voucher.ts
var IN = /te\s*yape(?:aron|[oó])|te\s*plinearon|recibiste|te\s*envi(?:[oó]|aron)|te\s*transfiri|te\s*(?:pag[oó]|pagaron|depositaron)|recibido\s+de|has\s+recibido|(?:abono|dep[oó]sito|transferencia)\s+recibid[oa]|cobraste/i;
var OUT = /yapeaste|plineaste|enviado\s+a|enviaste|pagaste|transferiste|pago\s+(?:exitoso|realizado)|operaci[oó]n\s+(?:exitosa|realizada)|transferencia\s+(?:exitosa|realizada)|env[ií]o\s+exitoso|realizad[oa]\s+con\s+[eé]xito|constancia\s+de\s+(?:pago|transferencia|operaci[oó]n)|beneficiario|destinatario|cuenta\s+(?:de\s+)?destino/i;
var CUR = String.raw`US\s?\$|(?:[Ss5§$])\s?[\/|Il]\s?\.?|\$`;
var NUM2 = String.raw`\d{1,3}(?:[,.]\d{3})+(?:[.,]\d{1,2})?|\d+(?:[.,]\d{1,2})?`;
var AMOUNT_RE2 = new RegExp(String.raw`(?<![\w/.,])(${CUR})\s*(${NUM2})(?![\d/]|[.,]\d)`, "g");
var AD_CONTEXT = /hasta|bienvenida|cashback|publicidad|\bgana\b|descuento|promo|oferta|sorteo/i;
var NOT_THE_AMOUNT = /comisi[oó]n|saldo|disponible|l[ií]mite|m[ií]nimo|m[aá]ximo|itf\b/i;
var TITLE = /yapeaste|plineaste|te\s*yape|te\s*plinearon|exitos[oa]|realizad[oa]|recibiste|constancia|enviaste|pagaste|transferiste/i;
var OTHER_BANKS = /banbif|pichincha|mibanco|scotiabank|banco de la naci[oó]n|caja\s+(?:arequipa|huancayo|piura|cusco|trujillo|sullana|ica|tacna|maynas)|falabella|ripley|\bgnb\b|citibank|alfin|compartamos|agrobanco|tunki|\bbim\b|ligo|lukita/i;
function toNumber(raw) {
  const s = raw.replace(/\s/g, "");
  const dec = s.match(/[.,](\d{1,2})$/);
  if (dec) {
    const int = s.slice(0, s.length - dec[0].length).replace(/[.,]/g, "");
    return Math.round(parseFloat(`${int}.${dec[1]}`) * 100) / 100;
  }
  return parseFloat(s.replace(/[.,]/g, ""));
}
function findAmount2(lines) {
  for (let i = 0; i < lines.length; i++) {
    if (NOT_THE_AMOUNT.test(lines[i])) continue;
    const around = `${lines[i - 1] ?? ""} ${lines[i]} ${lines[i + 1] ?? ""}`;
    if (AD_CONTEXT.test(around)) continue;
    for (const m of lines[i].matchAll(AMOUNT_RE2)) {
      const amount = toNumber(m[2]);
      if (!(amount > 0 && amount < 1e6)) continue;
      const currency = /\$/.test(m[1]) && !/^[Ss5§]/.test(m[1]) ? "USD" : "PEN";
      return { amount, currency, index: i };
    }
  }
  const title = lines.findIndex((l) => TITLE.test(l));
  if (title >= 0) {
    for (let i = title + 1; i <= title + 2 && i < lines.length; i++) {
      const m = lines[i].match(/^(\d{1,6}(?:[.,]\d{1,2})?)$/);
      if (m && toNumber(m[1]) > 0) return { amount: toNumber(m[1]), currency: "PEN", index: i };
    }
  }
  return null;
}
function bankOf(lines, text) {
  if (/yapeaste|te\s*yape/i.test(text)) return "yape";
  if (/plineaste|te\s*plinearon/i.test(text)) return "plin";
  const byName = (s) => {
    if (/bcp|banco de cr[eé]dito/i.test(s)) return "bcp";
    if (/in[tf]er[bv]ank|lnterbank/i.test(s)) return "interbank";
    if (/bbva/i.test(s)) return "bbva";
    if (/scotiabank/i.test(s)) return "scotiabank";
    if (OTHER_BANKS.test(s)) return "otro";
    return null;
  };
  const head = byName(lines.slice(0, 4).join(" "));
  if (head) return head;
  const anywhere = byName(text);
  if (anywhere) return anywhere;
  if (/\byape\b/i.test(text)) return "yape";
  if (/\bplin\b/i.test(text)) return "plin";
  return "otro";
}
var LABEL = /^(?:enviado\s+a|enviaste\s+a|pagaste\s+a|para\s*:|destinatario|beneficiario|nombre\s+del\s+beneficiario|recibido\s+de|remitente|de\s*:|comercio|empresa|establecimiento|pagado\s+a)\s*:?\s*(.*)$/i;
var NOT_A_NAME = /compartir|yapeaste|plineaste|exitos|operaci[oó]n|fecha|hora|c[oó]digo|datos|nro|n[uú]mero|destino|comisi[oó]n|reserva|mensaje|celular|gratis|desde|cuenta|constancia|realizad|recibiste|\d{3}/i;
function cleanName(raw) {
  const name = raw.replace(/\d[\d\s-]{5,}.*$/, "").replace(/[*|]/g, "").replace(/\s+/g, " ").trim();
  if (!/[a-záéíóúñ]{2,}/i.test(name)) return "";
  return name.toLowerCase().replace(/(^|\s)([a-záéíóúñ])/g, (_, s, c) => s + c.toUpperCase()).slice(0, 60);
}
function counterpart(lines, amountIndex) {
  for (let i = 0; i < lines.length; i++) {
    const m = lines[i].match(LABEL);
    if (!m) continue;
    const value = m[1].trim() || lines[i + 1] || "";
    const name = cleanName(value);
    if (name) return { name, labeled: lines[i].toLowerCase() };
  }
  for (let i = amountIndex + 1; i <= amountIndex + 2 && i < lines.length; i++) {
    if (NOT_A_NAME.test(lines[i])) continue;
    const name = cleanName(lines[i]);
    if (name && name.split(" ").length <= 5) return { name, labeled: "" };
  }
  return { name: "", labeled: "" };
}
function looksLikeVoucher(text) {
  return IN.test(text) || OUT.test(text);
}
function parseVoucher(text, receivedAt) {
  const normalized = normalizeText(text);
  if (!looksLikeVoucher(normalized)) return null;
  const lines = normalized.split("\n").map((l) => l.replace(/\s+/g, " ").trim()).filter(Boolean);
  const found = findAmount2(lines);
  if (!found) return null;
  const incoming = IN.test(normalized);
  const bank = bankOf(lines, normalized);
  const { name, labeled } = counterpart(lines, found.index);
  const isPayment = /comercio|empresa|establecimiento|pagaste|servicio/i.test(labeled + normalized);
  let kind;
  if (incoming) {
    kind = bank === "yape" ? "yape_recibido" : bank === "plin" ? "plin_recibido" : "transferencia";
  } else if (bank === "yape") {
    kind = "yape_enviado";
  } else if (/empresa|servicio/i.test(labeled)) {
    kind = "pago_servicio";
  } else if (/comercio|establecimiento/i.test(labeled)) {
    kind = "consumo";
  } else {
    kind = "transferencia";
  }
  const fallbackName = bank === "yape" ? "Yape" : bank === "plin" ? "Plin" : incoming ? "Ingreso" : "Transferencia";
  const merchant = (isPayment && !incoming && name ? cleanMerchant(name) : name) || fallbackName;
  const dateIdx = lines.findIndex((l) => parseDate(l, receivedAt));
  const date = dateIdx >= 0 ? parseDate(lines[dateIdx], receivedAt) : null;
  const time = date ? parseTime(lines[dateIdx]) ?? parseTime(lines[dateIdx + 1] ?? "") : null;
  const fromIdx = lines.findIndex((l) => /^desde\b/i.test(l));
  const from = fromIdx >= 0 ? lines.slice(fromIdx, fromIdx + 2).join(" ") : "";
  const sourceLast4 = from.match(/(\d{4})\s*$/)?.[1];
  const opLine = lines.findIndex(
    (l) => /(?:n(?:ro|[uú]mero|[º°o])\.?\s*de\s*operaci[oó]n|c[oó]digo\s+de\s+operaci[oó]n)/i.test(l)
  );
  const opId = opLine >= 0 ? `${lines[opLine]} ${lines[opLine + 1] ?? ""}`.match(/\b(\d{6,20})\b/)?.[1] : void 0;
  return {
    bank,
    kind,
    type: incoming ? "ingreso" : "gasto",
    amount: found.amount,
    currency: found.currency,
    merchant: merchant.slice(0, 120),
    date: date ?? localDate(receivedAt),
    time: date ? time : localTime(receivedAt),
    ...sourceLast4 && !incoming ? { cardLast4: sourceLast4 } : {},
    operationId: opId,
    suggestedCategory: isPayment && !incoming ? suggestCategory(merchant, normalized) : null,
    recurring: false
  };
}

// src/lib/auto/index.ts
var TRUSTED_EMAIL_DOMAINS = {
  "notificacionesbcp.com.pe": "bcp",
  "bcp.com.pe": "bcp",
  "bbva.com.pe": "bbva",
  "netinterbank.com.pe": "interbank",
  "interbank.pe": "interbank",
  "yape.pe": "yape"
};
var PARSERS = {
  bcp: [parseBcp, parseYape],
  // Yape emails are sent through BCP infrastructure
  bbva: [parseBbva],
  interbank: [parseInterbank],
  yape: [parseYape],
  plin: [parseInterbank],
  scotiabank: [],
  otro: []
};
function bankForEmail(sender) {
  const domain = sender?.match(/@([a-z0-9.-]+)>?\s*$/i)?.[1]?.toLowerCase();
  if (!domain) return null;
  for (const [d, bank] of Object.entries(TRUSTED_EMAIL_DOMAINS)) {
    if (domain === d || domain.endsWith(`.${d}`)) return bank;
  }
  return null;
}
function bankForApp(sender) {
  const s = (sender ?? "").toLowerCase();
  if (/yape/.test(s)) return "yape";
  if (/interbank/.test(s)) return "interbank";
  if (/bcp|viabcp|com\.bcp/.test(s)) return "bcp";
  if (/bbva/.test(s)) return "bbva";
  if (/plin/.test(s)) return "plin";
  return null;
}
function parseBankMessage(input) {
  if (!input.text?.trim()) return null;
  const msg = { ...input, text: stripBoldMarkers(input.text) };
  let candidates;
  if (msg.source === "email") {
    const bank = bankForEmail(msg.sender);
    if (!bank) return null;
    candidates = PARSERS[bank];
  } else {
    const bank = bankForApp(msg.sender);
    candidates = bank ? PARSERS[bank] : [parseInterbank, parseBcp, parseBbva, parseYape];
  }
  for (const parse of candidates) {
    const result = parse(msg);
    if (result) return result;
  }
  if (msg.source !== "text") return null;
  const voucher = looksLikeVoucher(msg.text);
  if (voucher) {
    const parsed = parseVoucher(msg.text, msg.receivedAt);
    if (parsed) return parsed;
  }
  if (/\btotal\b/i.test(msg.text)) {
    const receipt = parseReceipt(msg.text, msg.receivedAt);
    if (receipt) return receipt;
  }
  if (voucher) return null;
  return parseFreeText(msg.text, msg.receivedAt);
}
function operationKey(m) {
  return m.operationId ? `${m.bank}:${m.operationId}` : null;
}
function minutes(m) {
  if (!m.time) return null;
  const [h, mi] = m.time.split(":").map(Number);
  return (/* @__PURE__ */ new Date(`${m.date}T00:00:00`)).getTime() / 6e4 + h * 60 + mi;
}
function isLikelyDuplicate(a, b, windowMinutes = 15) {
  const ka = operationKey(a);
  const kb = operationKey(b);
  if (ka && kb) return ka === kb;
  if (a.type !== b.type || a.currency !== b.currency || a.amount !== b.amount) return false;
  const ma = minutes(a);
  const mb = minutes(b);
  if (ma !== null && mb !== null) {
    if (Math.abs(ma - mb) > windowMinutes) return false;
  } else if (a.date !== b.date) {
    return false;
  }
  return sameMerchant(a.merchant, b.merchant);
}
export {
  bankForEmail,
  isLikelyDuplicate,
  operationKey,
  parseBankMessage
};
